#ifndef DEFUNBOBENGINE_EVENT_TYPE_HPP
#define DEFUNBOBENGINE_EVENT_TYPE_HPP

enum class EventType {
    KEYPRESSED,
    KEYRELEASED,
    MOUSEPRESSED,
    MOUSECLICKED,
    MOUSERELEASED,
    MOUSEMOVED,
};

#endif // DEFUNBOBENGINE_EVENT_TYPE_HPP
