name: CMake Build

on:
    push:
        branches:
            - main
            - development
            - staging

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install CMake
              run: sudo apt-get install -y cmake

            - name: Build
              run: cmake . && make

            - name: Archive build result
              uses: actions/upload-artifact@v2
              with:
                  name: build-result
                  path: |
                      ./build
