name: CMake Build

on:
  push:
    branches:
      - main
      - development
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Install vcpkg
        run: |
          wget -qO vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz
          tar -xf vcpkg.tar.gz
          cd vcpkg-master
          ./bootstrap-vcpkg.sh

      - name: Install dependencies
        run: ./vcpkg-master/vcpkg install --triplet x64-linux --feature-flags=manifests

      - name: Build
        run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg-master/scripts/buildsystems/vcpkg.cmake -S . -B build && cmake --build build

      - name: Archive build result
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: |
            ./build
