name: Doxygen

on:
  push:
    branches:
      - main
      - staging
      - development
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Cache docs
        uses: actions/cache@v2
        with:
          path: docs
          key: docs-cache-${{ runner.os }}

      - name: Get branch name or tag name
        id: extract_info
        run: |
          ref=${{ github.ref }}
          IFS='/' read -ra ADDR <<< "$ref"
          echo "BUILD_INFO=${ADDR[2]}" >> $GITHUB_ENV

      - name: Update Doxygen version
        run: |
          sed -i "s/PROJECT_NUMBER.*/PROJECT_NUMBER = $GITHUB_SHA/" Doxyfile
          sed -i "s/OUTPUT_DIRECTORY.*/OUTPUT_DIRECTORY = docs\/${{ env.BUILD_INFO }}/" Doxyfile

      - name: Generate Doxygen documentation
        run: |
          if [ ! -d "docs/${{ env.BUILD_INFO }}" ]; then
            mkdir -p docs/${{ env.BUILD_INFO }}
          fi
          doxygen Doxyfile

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
