name: DeFunBobEngine Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache vcpkg
        uses: actions/cache@v2
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Install CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-Linux-x86_64.sh
          sudo sh cmake-3.27.0-Linux-x86_64.sh --skip-license --prefix=/usr/local

      - name: Install vcpkg
        run: |
          if [ ! -d "./vcpkg" ] ; then
            git clone https://github.com/Microsoft/vcpkg.git vcpkg
          else
            git -C vcpkg pull
          fi
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: ./vcpkg/vcpkg install --triplet x64-linux --feature-flags=manifests

      - name: Build
        run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build && cmake --build build

      - name: Create SDK archives
        run: | 
          zip -r sdk.zip include
          tar -czf sdk.tar.gz include
          
      - name: Generate checksum for sdk.zip
        run: sha256sum sdk.zip > sdk.zip.sha256

      - name: Generate checksum for sdk.tar.gz
        run: sha256sum sdk.tar.gz > sdk.tar.gz.sha256

      - name: Generate checksum for DeFunBobEngine
        run: cd build && sha256sum DeFunBobEngine > DeFunBobEngine.sha256

      - name: Upload compiled binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/DeFunBobEngine
          asset_name: DeFunBobEngine
          tag: ${{ github.ref }}

      - name: Upload SDK archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sdk.zip
          asset_name: DeFunBobEngine-sdk.zip
          tag: ${{ github.ref }}

      - name: Upload SDK tarball
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sdk.tar.gz
          asset_name: DeFunBobEngine-sdk.tar.gz
          tag: ${{ github.ref }}

      - name: Upload binary checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/DeFunBobEngine.sha256
          asset_name: DeFunBobEngine.sha256
          tag: ${{ github.ref }}

      - name: Upload SDK archive checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sdk.zip.sha256
          asset_name: DeFunBobEngine-sdk.zip.sha256
          tag: ${{ github.ref }}

      - name: Upload SDK tarball checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sdk.tar.gz.sha256
          asset_name: DeFunBobEngine-sdk.tar.gz.sha256
          tag: ${{ github.ref }}
