name: DeFunBobEngine Release Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache vcpkg
        uses: actions/cache@v2
        with:
          path: vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-Linux-x86_64.sh
          sudo sh cmake-3.27.0-Linux-x86_64.sh --skip-license --prefix=/usr/local

      - name: Install vcpkg
        run: |
          if [ ! -d "./vcpkg" ] ; then
            git clone https://github.com/Microsoft/vcpkg.git vcpkg
          else
            git -C vcpkg pull
          fi
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: ./vcpkg/vcpkg install --triplet x64-linux --feature-flags=manifests

      - name: Build
        run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build && cmake --build build

      - name: Create SDK archives
        run: | 
          zip -r sdk.zip include
          tar -czf sdk.tar.gz include

      - name: Upload compiled binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: build/DeFunBobEngine
          asset_name: DeFunBobEngine
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            Compiled binaries for ${{ github.ref }}

      - name: Upload SDK archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: sdk.zip
          asset_name: DeFunBobEngine-sdk.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            SDK archive for ${{ github.ref }}

      - name: Upload SDK tarball
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: sdk.tar.gz
          asset_name: DeFunBobEngine-sdk.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            SDK tarball for ${{ github.ref }}
