name: DeFunBobEngine Release Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache vcpkg
        uses: actions/cache@v2
        with:
          path: vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-Linux-x86_64.sh
          sudo sh cmake-3.27.0-Linux-x86_64.sh --skip-license --prefix=/usr/local

      - name: Install vcpkg
        run: |
          if [ ! -d "./vcpkg" ] ; then
            git clone https://github.com/Microsoft/vcpkg.git vcpkg
          else
            git -C vcpkg pull
          fi
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: ./vcpkg/vcpkg install --triplet x64-linux --feature-flags=manifests

      - name: Build
        run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build && cmake --build build

      - name: Create SDK archives
        run: | 
          zip -r sdk.zip include
          tar -czf sdk.tar.gz include

      - name: Generate release body
        id: generate_release_body
        run: |
          BODY=$(git log --pretty=format:'- %s' $(git describe --tags --abbrev=0)..HEAD)
          if [ -z "$BODY" ]; then
            BODY="Release ${{ github.ref }}"
          fi
          echo "BODY=${BODY}" >> $GITHUB_ENV

      - name: Create library release
        id: create_library
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.BODY }}
          draft: false
          prerelease: false

      - name: Create SDK ZIP release
        id: create_sdk_zip
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.BODY }}
          draft: false
          prerelease: false

      - name: Create SDK tar.gz release
        id: create_sdk_tar_gz
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.BODY }}
          draft: false
          prerelease: false

      - name: Upload library binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_library.outputs.upload_url }}
          asset_path: ./build/DeFunBobEngine
          asset_name: DeFunBobEngine
          asset_content_type: application/octet-stream

      - name: Upload SDK zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_sdk_zip.outputs.upload_url }}
          asset_path: ./sdk.zip
          asset_name: DeFunBobEngine-sdk.zip
          asset_content_type: application/zip

      - name: Upload SDK tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_sdk_tar_gz.outputs.upload_url }}
          asset_path: ./sdk.tar.gz
          asset_name: DeFunBobEngine-sdk.tar.gz
          asset_content_type: application/gzip
